extends: eslint-config-dmitmel/presets/node
env:
  node: true
  browser: true
parserOptions:
  sourceType: module

rules:
  func-names: off
  node/no-unsupported-features/es-syntax:
    - error
    - ignores:
        - modules
        - dynamicImport
  node/no-unpublished-require: off

overrides:
  - files: '**/*.{ts,tsx}'
    extends: eslint-config-dmitmel/presets/typescript-with-type-checking-addon

  - files: 'src/**/*.{ts,tsx}'
    parserOptions:
      project: 'tsconfig.json'

  - files: 'src/mod/**/*.js'
    globals:
      sc: true
      ig: true
      ccmod: true
